version: "3.9"
services:
    mysql:
        image: mysql:8.0.26
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=lab1
    lab2:
        image: dannekun/bank:0.0.1
        environment:
            - MYSQL_HOST=mysql
        ports:
            - "8080:8082"
        links:
            - mysql
    swagger:
        image: daneidmark/risk:0.0.1
        ports:
            - "8082:8080"